name = "glerd_valid"
version = "0.1.1"
description = "Gleam Record validators using Glerd metadata"
licences = ["MIT"]
repository = { type = "github", user = "darky", repo = "glerd-valid" }
gleam = ">= 1.3.2"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleamyshell = ">= 2.0.0"
glerd = ">= 4.2.6"
justin = ">= 1.0.1"
simplifile = ">= 1.7.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
